# ApplicationGasulator 
edmunds_key: xcs69p6sfvqx4dg3tupjg8hn 
edmunds_secret: 6YHqf4jH3kZSdyehn2Ygtavg 

# Status: active 
# Created: 3 seconds ago

# Key Rate Limits
# 2	 Calls per second
# 5,000	 Calls per day
